version: '3.8'

services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: clearstack
      POSTGRES_PASSWORD: password
      POSTGRES_DB: clearstack
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U clearstack"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql://clearstack:password@db:5432/clearstack?schema=public
      JWT_SECRET: changeme-super-secret-key
      PORT: 3000
      NODE_ENV: production
    ports:
      - "3000:3000"
    volumes:
      - ./backend/prisma:/app/backend/prisma

  adminer:
    image: adminer:4.8.1
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      ADMINER_DEFAULT_SERVER: db

volumes:
  pgdata: