# path: backend/docker-compose.yml
version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: clearstack_postgres
    environment:
      POSTGRES_DB: clearstack_dev
      POSTGRES_USER: clearstack
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/schema.sql:/docker-entrypoint-initdb.d/01-schema.sql
      - ./database/schema_patch.sql:/docker-entrypoint-initdb.d/02-patch.sql
    networks:
      - clearstack

  adminer:
    image: adminer:4.8.1
    container_name: clearstack_adminer
    ports:
      - "8080:8080"
    environment:
      ADMINER_DEFAULT_SERVER: postgres
    networks:
      - clearstack
    depends_on:
      - postgres

volumes:
  postgres_data:

networks:
  clearstack:
    driver: bridge